### ISSUE TITLE
error  'web_progress.ProgressMenu' not found

### ISSUE THREAD

**Issue by rccardero** [gmarczynski/odoo-web-progress#12]
Hello, what can be happening that sometimes just after installing it in version 13 I get the following error when trying to refresh Odoo ?:
Error: QWeb2: Template 'web_progress.ProgressMenu' not found
     at Object.exception (https://geo.odoo.lat/web/content/67473-773416e/web.assets_common.js:3692:7)
     at Engine._render (https://geo.odoo.lat/web/content/67473-773416e/web.assets_common.js:3737:103)
     at Engine.render (https://geo.odoo.lat/web/content/67473-773416e/web.assets_common.js:3733:151)
     at Class.renderElement (https://geo.odoo.lat/web/content/67473-773416e/web.assets_common.js:4097:1178)
     at https://geo.odoo.lat/web/content/67473-773416e/web.assets_common.js:4107:6

**Comment by gmarczynski** [comment]
I got the same problem once with one database under Odoo v 11.0 CE. Only one db out of couple of thousands that I used with this module installed in. 

Unfortunately I did not find any reason for this error to show up. After 1-2 hours of investigation I gave up.

**Comment by mealhero** [comment]
I have the same on Odoo 12 Enterprise (self hosted).

**Comment by reinaldoBloopark** [comment]
I had the same issue in Odoo14. I updated "base" module and I could fix it.
