### ISSUE TITLE
16.0: Exception on using export feature

### ISSUE THREAD

**Issue by pafnow** [gmarczynski/odoo-web-progress#27]
Hi,
After installing the module, when I try to use the export action or export all  button, I get below error

![image](https://user-images.githubusercontent.com/8747037/216677981-43386455-67a9-466a-b052-dd88803a8cbb.png)

```
UncaughtPromiseError > SyntaxError
Promesse non interceptée > "undefined" is not valid JSON
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Function._download (http://localhost:8069/web/assets/debug/web.assets_backend.js:181764:30) (/web_progress/static/src/js/rpc_service.js:23)
    at download (http://localhost:8069/web/assets/debug/web.assets_backend.js:10055:21) (/web/static/src/core/network/download.js:455)
    at ListController.downloadExport (http://localhost:8069/web/assets/debug/web.assets_backend.js:45531:15) (/web/static/src/views/list/list_controller.js:349)
    at ExportDataDialog.onClickExportButton (http://localhost:8069/web/assets/debug/web.assets_backend.js:56420:26) (/web/static/src/views/view_dialogs/export_data_dialog.js:306)
    at Object.mainEventHandler (http://localhost:8069/web/assets/debug/web.assets_common.js:21650:25) (/web/static/lib/owl/owl.js:5480)
    at HTMLButtonElement.listener (http://localhost:8069/web/assets/debug/web.assets_common.js:16504:20) (/web/static/lib/owl/owl.js:334)
```

**Comment by gmarczynski** [comment]
Thank you. Should be fixed now. 
As a bonus I added UI blocking during export, because according to my tests the UI was never blocked.

**Comment by pafnow** [comment]
I confirm it is now working properly.
Thanks for your fast fix, cheers
