### ISSUE TITLE
16.0: Bug when exporting translation

### ISSUE THREAD

**Issue by pafnow** [gmarczynski/odoo-web-progress#30]
Hello,

New bug found when exporting a translation file (Settings / Translations / Export translation)
In the window where we click to download the .pot file, when I click to download I get an exception

![image](https://user-images.githubusercontent.com/8747037/216958417-ef1921df-ab61-4cad-ae6a-3a07a0be5bb0.png)

![image](https://user-images.githubusercontent.com/8747037/216958445-11349d04-0fcf-45ae-a8d5-764487e1d3e3.png)

```
UncaughtPromiseError > SyntaxError
Uncaught Promise > "undefined" is not valid JSON
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Function._download (http://localhost:8069/web/assets/debug/web.assets_backend.js:181764:30) (/web_progress/static/src/js/rpc_service.js:23)
    at download (http://localhost:8069/web/assets/debug/web.assets_backend.js:10055:21) (/web/static/src/core/network/download.js:455)
    at BinaryField.onFileDownload (http://localhost:8069/web/assets/debug/web.assets_backend.js:28724:15) (/web/static/src/views/fields/binary/binary_field.js:40)
    at Object.mainEventHandler (http://localhost:8069/web/assets/debug/web.assets_common.js:21650:25) (/web/static/lib/owl/owl.js:5480)
    at HTMLAnchorElement.listener (http://localhost:8069/web/assets/debug/web.assets_common.js:16504:20) (/web/static/lib/owl/owl.js:334)
```

Let me know if you need any information more.
Have a nice day

**Comment by gmarczynski** [comment]
Hello,

Right. Thank you!

Fixed.
