### ISSUE TITLE
Binary field causing issue

### ISSUE THREAD

**Issue by amineamri3** [gmarczynski/odoo-web-progress#31]
when downloading a binary file it causes an error and a permanent loading in the UI, after some investigation it seems like the binary file is passed directly to the "get_file" function and causes the json.Parse() to throw an error.

`Uncaught SyntaxError: Unexpected token 'J', "JVBERi0xLj"... is not valid JSON
http://localhost:8069/web#id=5&action=315&model=request.request&view_type=form&cids=&menu_id=198:1
Traceback:
SyntaxError: Unexpected token 'J', "JVBERi0xLj"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.get_file (http://localhost:8069/web/content/668-a4f8445/web.assets_backend.js:6582:108)
    at Class.get_file (http://localhost:8069/web/content/656-a1c90e6/web.assets_common.js:4876:249)
    at Class.on_save_as (http://localhost:8069/web/content/668-a4f8445/web.assets_backend.js:982:1599)
    at Class.click (http://localhost:8069/web/content/668-a4f8445/web.assets_backend.js:982:413)
    at HTMLAnchorElement.<anonymous> (http://localhost:8069/web/content/656-a1c90e6/web.assets_common.js:4789:11)
    at HTMLAnchorElement.dispatch (http://localhost:8069/web/content/656-a1c90e6/web.assets_common.js:1740:447)
    at elemData.handle (http://localhost:8069/web/content/656-a1c90e6/web.assets_common.js:1726:166)`

**Comment by gmarczynski** [comment]
Hello, thank you for the report. 

I was unable to reproduce your problem with version 16.0.
Can you please share your Odoo version?

Thanks!

**Comment by amineamri3** [comment]
Odoo version 14

**Comment by gmarczynski** [comment]
Thank you. I will have a look.

**Comment by emadco88** [comment]
Hello,

I’m also using Odoo 15.0 and I encountered this issue in the get_file function.
The problem occurs when trying to download a binary file from a One2many record.

After pulling the latest updates - it did not solve it - but I was able to work around it using the following fix (with help from ChatGPT):
```
// --- edited get_file (replace the original function) ---
    function get_file(options) {
        var complete = options.complete;

        // Only try to handle progress when options.data.data is a real JSON string
        var parsed = null;
        if (options && options.data && Object.prototype.hasOwnProperty.call(options.data, 'data')) {
            parsed = safeParseJsonMaybe(options.data.data);
        }

        if (parsed) {
            var context = ensureContextContainer(parsed);
            if (complete && context) {
                var progress_code = pseudoUuid();
                context.progress_code = progress_code;

                options.complete = function () {
                    core.bus.trigger('rpc_progress_result', progress_code);
                    complete();
                };
                core.bus.trigger('rpc_progress_request', progress_code);

                // keep the payload as a JSON string (as expected by the target route)
                options.data.data = JSON.stringify(parsed);
            }
        }

        return ajax_get_file(options);
    }

```

I hope this helps. Please let me know if the patch looks okay or if there’s a better approach.

Thanks!
