### ISSUE TITLE
16.0: Error when printing report

### ISSUE THREAD

**Issue by pafnow** [gmarczynski/odoo-web-progress#32]
Hello,

I encountered a new issue this morning while trying to print report.

Here is how to reproduce:
- Go to Settings / General Settings
- Under Companies / Document Layout, click on Preview Document
- This should print the default company layout in PDF using wkhtmltopdf

I then get this error:
![image](https://user-images.githubusercontent.com/8747037/217479782-36f35f52-6b2f-4141-9cc0-1943cf75d926.png)
```
TypeError: Cannot read properties of undefined (reading 'progress_code')
    at Function._download (http://localhost:8069/web/assets/debug/web.assets_backend.js:181767:66) (/web_progress/static/src/js/rpc_service.js:26)
    at download (http://localhost:8069/web/assets/debug/web.assets_backend.js:10055:21) (/web/static/src/core/network/download.js:455)
    at _triggerDownload (http://localhost:8069/web/assets/debug/web.assets_backend.js:58827:19) (/web/static/src/webclient/actions/action_service.js:1072)
    at _executeReportAction (http://localhost:8069/web/assets/debug/web.assets_backend.js:58902:24) (/web/static/src/webclient/actions/action_service.js:1147)
    at async Object.doActionButton (http://localhost:8069/web/assets/debug/web.assets_backend.js:59075:9) (/web/static/src/webclient/actions/action_service.js:1320)
    at async execute (http://localhost:8069/web/assets/debug/web.assets_backend.js:55550:21) (/web/static/src/views/view_button/view_button_hook.js:98)
```

---

I tried a dirty fix to pass thru, consisting in commenting the override of function `function _download(options)` defined here https://github.com/gmarczynski/odoo-web-progress/blob/16.0/web_progress/static/src/js/rpc_service.js

I then get another error message:
![image](https://user-images.githubusercontent.com/8747037/217480617-55ad5f48-f6e5-4857-ad47-1ed384f216ad.png)
```
Traceback (most recent call last):
  File "/mnt/c/Users/Damien/odoo16/16.0/addons/web/controllers/report.py", line 123, in report_download
    response = self.report_routes(reportname, converter=converter, context=context, **data)
  File "/mnt/c/Users/Damien/odoo16/16.0/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/mnt/c/Users/Damien/odoo16/16.0/addons/web/controllers/report.py", line 45, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
  File "/mnt/c/Users/Damien/odoo16/16.0/addons/account/models/ir_actions_report.py", line 54, in _render_qweb_pdf
    return super()._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
TypeError: IrActionsReport._render_qweb_pdf() got multiple values for argument 'res_ids'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8069/web/assets/debug/web.assets_backend.js:10232:19) (/web/static/src/core/network/rpc_service.js:34)
    at decoder.onload (http://localhost:8069/web/assets/debug/web.assets_backend.js:10120:29) (/web/static/src/core/network/download.js:520)
```

Let me know if anything I can help
Thanks again

**Comment by pafnow** [comment]
I found the root cause of the second part of the issue, the _render_qweb_pdf function signature has changed, therefore the code of the module need to adapt

```
    def _render_qweb_pdf(self, report_ref, res_ids=None, data=None):
        """
        Add progress_iter to the context in order to track progress of iterations inside report generation method
        """
        self.web_progress_percent(30, 'Rendering PDF')
        return super(IrActionsReport, self)._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
```

For the first one, I made a dirty fix but I don't get any progress bar so I think a better one exist :)

**Comment by gmarczynski** [comment]
Thank you. Should be fixed now.
